const $=(q,r)=> (r||document).querySelector(q); const $$=(q,r)=> Array.from((r||document).querySelectorAll(q));
const fmtNum=x=>{const n=Number(x);return isFinite(n)?n.toLocaleString('it-IT'):'—'}; const fmtTime=iso=>{try{return new Date(iso).toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'})}catch(_){return'—:—'}};
let LAST_MODEL=null;
function renderState(m){ const chip=$('#chipState'); const st=(m.state||'').toUpperCase(); if(chip){ const cls=(window.STATE_CLASS&&STATE_CLASS[st])||'neutral'; chip.className='chip state '+cls; chip.textContent=st.replace('_',' '); const hs=$('#houseStatus'); if(hs) hs.textContent=m.notte?'Notte':'Giorno'; } const sb=$('#stateBanner'); if(sb){ const map={'COMFY_DAY':'sb-comfy-day','COMFY_NIGHT':'sb-comfy-night','SECURITY_DAY':'sb-security-day','SECURITY_NIGHT':'sb-security-night'}; sb.className='state-banner '+(map[st]||'sb-security-day'); sb.textContent=st.replace('_',' ');} }
function renderPeople(m){ const arr=Array.isArray(m.people)?m.people:[]; const n=arr.filter(p=>p.onlineSmart||p.onlineRaw).length; const ppl=$('#peopleOnline'); if(ppl) ppl.textContent=n; const chips=$('#peopleChips'); if(chips){ chips.innerHTML=''; arr.forEach(p=>{ const on=(p.onlineSmart||p.onlineRaw); const el=document.createElement('div'); el.className='chip'; el.innerHTML=`<span class="dot ${on?'on':'off'}"></span>${p.name}`; chips.appendChild(el); }); } }
function setWeatherUI(obj){ const temp=$('#tempValue'); if(temp&&typeof obj.tempC==='number') temp.textContent=Math.round(obj.tempC); const hum=$('#humValue'); if(hum&&typeof obj.humidity==='number') hum.textContent=Math.round(obj.humidity); const wt=$('#weatherTemp'); if(wt&&typeof obj.tempC==='number') wt.textContent=Math.round(obj.tempC)+'°C'; const wk=$('#windKmh'); if(wk&&typeof obj.windKmh==='number') wk.textContent=Math.round(obj.windKmh)+' km/h'; const emoji=$('#weatherEmoji'); if(emoji&&obj.icon!=null){ const m=(window.mapWeatherCode?mapWeatherCode(obj.icon):{icon:''}); emoji.textContent=(m&&m.icon)||''; } const prov=$('#weatherProvider'); if(prov) prov.textContent=(obj.provider||'—'); }
async function getLatLonFromConfigOrBrowser(){ const cfg=(typeof CONFIG!=='undefined'&&CONFIG&&CONFIG.WEATHER)?CONFIG.WEATHER:{}; if(typeof cfg.lat==='number'&&typeof cfg.lon==='number') return {lat:cfg.lat,lon:cfg.lon,tz:cfg.tz||'Europe/Rome'}; return await new Promise((resolve,reject)=>{ if(!('geolocation' in navigator)) return reject(new Error('no geolocation')); navigator.geolocation.getCurrentPosition(p=>resolve({lat:p.coords.latitude,lon:p.coords.longitude,tz:cfg.tz||'Europe/Rome'}),reject,{timeout:3000,maximumAge:600000}); }); }
async function fetchWeatherClient(){ const {lat,lon,tz}=await getLatLonFromConfigOrBrowser(); const url='https://api.open-meteo.com/v1/forecast?latitude='+encodeURIComponent(lat)+'&longitude='+encodeURIComponent(lon)+'&current=temperature_2m,relative_humidity_2m,weather_code,wind_speed_10m&timezone='+encodeURIComponent(tz||'Europe/Rome'); const r=await fetch(url); if(!r.ok) throw new Error('Open-Meteo HTTP '+r.status); const js=await r.json(); const cur=(js&&js.current)||{}; return { tempC: (typeof cur.temperature_2m==='number')?cur.temperature_2m:null, humidity: (typeof cur.relative_humidity_2m==='number')?cur.relative_humidity_2m:null, icon: (cur.weather_code!=null)?String(cur.weather_code):'', windKmh: (typeof cur.wind_speed_10m==='number')?cur.wind_speed_10m:null, provider:'Open‑Meteo' }; }
function renderWeather(m){ const w=(m&&m.weather)||{}; setWeatherUI({ tempC:w.tempC, humidity:w.humidity, icon:w.icon, provider:w.provider, windKmh:w.windKmh}); }
async function ensureWeatherFallback(model){ try{ const force=!!(CONFIG&&CONFIG.WEATHER&&CONFIG.WEATHER.forceClient); const has=(model&&model.weather&&(typeof model.weather.tempC==='number'||typeof model.weather.humidity==='number')); if(has&&!force){ setWeatherUI(model.weather); return; } const w=await fetchWeatherClient(); setWeatherUI(w);}catch(e){ console.warn('Weather client fallback failed:',e);} }
function renderEnergy(m){ const k=(m.energy&&m.energy.kwh!=null)?m.energy.kwh:null; const ek=$('#energyKwh'); if(ek) ek.textContent=(k==null?'—':fmtNum(k)); }
function getShuttersUp(){ try{ return localStorage.getItem('ui_shutters_up')==='1'; }catch(_){ return false; } }
function setShuttersUp(v){ try{ localStorage.setItem('ui_shutters_up', v?'1':'0'); }catch(_){ } }
function favGlyph(id){ const map={ tapparelle:'icons/st/glyph-shutter.svg', piante:'icons/st/glyph-plant.svg', vacanza:'icons/st/glyph-suit.svg', override:'icons/st/glyph-moon.svg' }; return map[id]||'icons/st/glyph-generic.svg'; }
function favActionIcon(kind){ return (kind==='action')?'icons/st/ui-play.svg':'icons/st/ui-power.svg'; }
function renderFavorites(m){ const grid=$('#favoritesGrid'); if(!grid) return; grid.innerHTML=''; (CONFIG.FAVORITES||[]).forEach(f=>{ let isOn=(f.kind==='toggle'&&f.stateKey&&!!m[f.stateKey]); if(f.id==='tapparelle'){ isOn=getShuttersUp(); }
  const status=(f.id==='tapparelle')?(isOn?'Aperte':'Chiuse'):(f.kind==='toggle'?(isOn?'On':'Off'):'');
  const tile=document.createElement('article'); tile.className='fav'+(isOn?' active':''); tile.innerHTML=`
    <div class="glyph" style="background:${f.id==='piante'?'#e6f8ed':f.id==='tapparelle'?'#e7f2ff':f.id==='vacanza'?'#efe7ff':'#eef0f6'}">
      <img src="${favGlyph(f.id)}" alt="ico">
    </div>
    <button class="action-btn" aria-label="${f.kind==='action'?'Esegui':'Accendi/Spegni'}"><img src="${favActionIcon(f.kind)}" alt="act"></button>
    <div class="title">${f.label}</div>
    <div class="subtitle">${f.subtitle||''}</div>
    <div class="status">${status}</div>`;
  tile.addEventListener('click',(ev)=>{ if(ev.target.closest('.action-btn')) return; if(f.id==='piante'){ callAdmin('piante',{},()=>{},()=>{}); return; } if(f.id==='tapparelle'){ const next=!isOn; callAdmin(next?'alza_tutto':'abbassa_tutto',{},()=>{},()=>{}); setShuttersUp(next); setTimeout(loadAll,800);} });
  tile.querySelector('.action-btn').addEventListener('click',(ev)=>{ ev.stopPropagation(); if(f.id==='tapparelle'){ const next=!isOn; callAdmin(next?'alza_tutto':'abbassa_tutto',{},()=>{},()=>{}); setShuttersUp(next); setTimeout(loadAll,800); return; } if(f.kind==='toggle' && f.toggleEvent){ const next=!isOn; callAdmin(f.toggleEvent,{value:String(next)},()=> setTimeout(loadAll,400), ()=>{}); } if(f.kind==='action' && f.event){ callAdmin(f.event,{},()=>{},()=>{}); } });
  grid.appendChild(tile); }); }
function renderVimar(m){ const v=m.vimar||{shutters:[],thermostats:[],hvac:[]}; const sh=$('#vimarShutters'); if(sh){ sh.innerHTML=''; v.shutters.forEach(x=>{ const row=document.createElement('div'); row.className='row'; row.innerHTML=`<div><div class='title'>${x.name||x.id||'—'}</div><div class='sub'>${x.room||''} ${x.online?'· Online':'· Offline'}</div></div><div class='controls'><button class='small-btn' data-cmd='up'>Su</button><button class='small-btn' data-cmd='stop'>Stop</button><button class='small-btn' data-cmd='down'>Giu</button></div>`; row.querySelectorAll('button').forEach(b=> b.addEventListener('click',()=> callAdmin('vimar_shutter',{id:x.id,cmd:b.getAttribute('data-cmd')},()=>{},()=>{}) )); sh.appendChild(row); }); } const th=$('#vimarThermo'); if(th){ th.innerHTML=''; v.thermostats.forEach(x=>{ const row=document.createElement('div'); row.className='row'; row.innerHTML=`<div><div class='title'>${x.name||x.id||'—'}</div><div class='sub'>${x.room||''} · T=${x.temp??'—'}° · Set=${x.setpoint??'—'}° · ${x.mode||''}</div></div><div class='controls'><button class='small-btn' data-op='dec'>-</button><button class='small-btn' data-op='inc'>+</button><button class='small-btn' data-op='modeNext'>Mode</button></div>`; row.querySelectorAll('button').forEach(b=> b.addEventListener('click',()=> callAdmin('vimar_thermo',{id:x.id,op:b.getAttribute('data-op').toLowerCase()},()=>{},()=>{}) )); th.appendChild(row); }); } const hv=$('#vimarHvac'); if(hv){ hv.innerHTML=''; v.hvac.forEach(x=>{ const row=document.createElement('div'); row.className='row'; row.innerHTML=`<div><div class='title'>${x.name||x.id||'—'}</div><div class='sub'>${x.room||''} · ${x.mode||''} · Set=${x.setpoint??'—'}° · Fan=${x.fan||''}</div></div><div class='controls'><button class='small-btn' data-op='powerToggle'>Power</button><button class='small-btn' data-op='dec'>-</button><button class='small-btn' data-op='inc'>+</button><button class='small-btn' data-op='modeNext'>Mode</button><button class='small-btn' data-op='fanNext'>Fan</button></div>`; row.querySelectorAll('button').forEach(b=> b.addEventListener('click',()=> callAdmin('vimar_hvac',{id:x.id,op:b.getAttribute('data-op')},()=>{},()=>{}) )); hv.appendChild(row); }); } }
function renderLogs(logs){ const list=$('#log'), empty=$('#logEmpty'); if(!list) return; list.innerHTML=''; if(!logs||!logs.length){ if(empty) empty.textContent='Nessun log recente.'; return;} if(empty) empty.textContent=''; logs.forEach(x=>{ const row=document.createElement('div'); row.className='row'; const ts=(x.ts?new Date(x.ts).toLocaleString('it-IT'):'—'); row.innerHTML=`<div><div class='title'>${x.code||'—'}<span class='sub'> · ${x.stato||''}</span></div><div class='sub'>${ts} · ${x.desc||''} ${x.note?('· '+x.note):''}</div></div>`; list.appendChild(row); }); }
function activateTab(t){$$('.tab').forEach(b=>b.classList.toggle('active',b.getAttribute('data-target')===t));$$('.view').forEach(v=>v.classList.toggle('active',v.id==='view-'+t));window.scrollTo({top:0,behavior:'smooth'});} 
function loadAll(){ fetchModel((m)=>{ LAST_MODEL=m; try{ renderState(m); renderPeople(m); renderWeather(m); renderEnergy(m); renderFavorites(m); renderVimar(m); ensureWeatherFallback(m); // --- indicatori errori log ---
  const err=(m.alerts && Number(m.alerts.logErrors))||0; const dot=document.getElementById('dotLog'); if(dot) dot.hidden=!(err>0); const badge=document.getElementById('badgeLog'); if(badge) badge.hidden=(err<=0); const ts=$('#ts'); if(ts) ts.textContent='Aggiornamento: '+fmtTime(m.meta&&m.meta.nowIso); }catch(e){console.error(e);} }, (e)=>{ console.error('Model error',e); }); }
function loadLogs(){ fetchLogs(d=>renderLogs((d&&d.logs)||[]), e=>console.error('Logs error',e)); }

document.addEventListener('DOMContentLoaded',()=>{ const nm=document.getElementById('homeName'); if(nm) nm.textContent='Casa'; $$('.tab').forEach(t=>t.addEventListener('click',()=> activateTab(t.getAttribute('data-target')))); const kebab=document.getElementById('btnKebab'); if(kebab) kebab.addEventListener('click',()=> activateTab('log')); const add=document.getElementById('btnAdd'); if(add) add.addEventListener('click',()=> activateTab('devices')); loadAll(); loadLogs(); if(CONFIG && CONFIG.AUTO_REFRESH_MS>0) setInterval(loadAll, CONFIG.AUTO_REFRESH_MS); });
